import AppKit
import ApplicationServices

struct ClipItem: Codable, Identifiable, Equatable {
    enum Kind: String, Codable { case text, image, files }

    var id = UUID()
    var kind: Kind
    var text: String?
    var image: String?
    var paths: [String]?
    var app: String?
    var date = Date()

    var preview: String {
        switch kind {
        case .text: (text ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        case .image: "Imagen"
        case .files: (paths ?? []).map { URL(fileURLWithPath: $0).lastPathComponent }.joined(separator: ", ")
        }
    }

    var imageURL: URL? { image.map { Paths.folder("Clipboard").appendingPathComponent($0) } }

    var link: URL? {
        guard kind == .text, let t = text?.trimmingCharacters(in: .whitespacesAndNewlines), !t.contains(" "),
              t.hasPrefix("http://") || t.hasPrefix("https://") else { return nil }
        return URL(string: t)
    }

    /// Parses #RGB / #RRGGBB so the row can show a swatch.
    var color: (r: Double, g: Double, b: Double)? {
        guard kind == .text, var hex = text?.trimmingCharacters(in: .whitespacesAndNewlines), hex.hasPrefix("#") else { return nil }
        hex.removeFirst()
        if hex.count == 3 { hex = hex.map { "\($0)\($0)" }.joined() }
        guard hex.count == 6, let v = UInt32(hex, radix: 16) else { return nil }
        return (Double((v >> 16) & 0xFF) / 255, Double((v >> 8) & 0xFF) / 255, Double(v & 0xFF) / 255)
    }
}

@MainActor
final class ClipboardStore: ObservableObject {
    static let shared = ClipboardStore()

    @Published private(set) var history: [ClipItem] = []
    @Published private(set) var saved: [ClipItem] = []
    @Published private(set) var lastCopied: UUID?

    private var changeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    private var saveGeneration = 0
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
    ]

    init() {
        history = Disk.load([ClipItem].self, "clipboard.json") ?? []
        saved = Disk.load([ClipItem].self, "snippets.json") ?? []
    }

    func demo(history: [ClipItem], saved: [ClipItem]) {
        self.history = history
        self.saved = saved
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { _ in
            MainActor.assumeIsolated { ClipboardStore.shared.poll() }
        }
        timer?.tolerance = 0.2
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != changeCount else { return }
        changeCount = pb.changeCount
        if Prefs.clipboardPaused { return }
        let types = pb.types ?? []
        if types.contains(where: { Self.ignoredTypes.contains($0.rawValue) }) { return }
        let app = NSWorkspace.shared.frontmostApplication?.localizedName

        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            insert(ClipItem(kind: .files, paths: urls.map(\.path), app: app))
        } else if let text = pb.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            insert(ClipItem(kind: .text, text: text, app: app))
        } else if let data = pb.data(forType: .png) ?? NSImage(pasteboard: pb)?.pngData {
            let name = UUID().uuidString + ".png"
            guard (try? data.write(to: Paths.folder("Clipboard").appendingPathComponent(name))) != nil else { return }
            insert(ClipItem(kind: .image, image: name, app: app))
        }
    }

    fileprivate func insert(_ item: ClipItem) {
        if item.kind != .image, let dupe = history.firstIndex(where: { $0.kind == item.kind && $0.text == item.text && $0.paths == item.paths }) {
            history.remove(at: dupe)
        }
        history.insert(item, at: 0)
        while history.count > max(20, AppSettings.shared.historySize) { discard(history.removeLast()) }
        scheduleSave()
    }

    /// Our own writes (notes, tools) shouldn't show up as history entries.
    func skipCurrentChange() { changeCount = NSPasteboard.general.changeCount }

    func copy(_ item: ClipItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text: pb.setString(item.text ?? "", forType: .string)
        case .image: if let url = item.imageURL, let img = NSImage(contentsOf: url) { pb.writeObjects([img]) }
        case .files: pb.writeObjects((item.paths ?? []).map { URL(fileURLWithPath: $0) as NSURL })
        }
        changeCount = pb.changeCount
        if let i = history.firstIndex(where: { $0.id == item.id }) {
            var moved = history.remove(at: i)
            moved.date = Date()
            history.insert(moved, at: 0)
            scheduleSave()
        }
        lastCopied = item.id
        Task { @MainActor in
            try? await Task.sleep(for: .seconds(1.2))
            if ClipboardStore.shared.lastCopied == item.id { ClipboardStore.shared.lastCopied = nil }
        }
        if Prefs.autoPaste && AXIsProcessTrusted() {
            NotchModel.shared.close()
            Paster.paste()
        }
    }

    /// ⌃⌥1…9: copy (and optionally paste) the Nth saved snippet.
    func copySaved(at index: Int) {
        guard saved.indices.contains(index) else { return }
        let item = saved[index]
        copy(item)
        if !(Prefs.autoPaste && AXIsProcessTrusted()) {
            NotchModel.shared.announce(Announcement(symbol: "doc.on.clipboard.fill", tint: .ok, title: "Copiado · ⌃⌥\(index + 1)",
                                                    subtitle: String(item.preview.prefix(60))))
        }
    }

    func recognizeText(_ item: ClipItem) {
        guard let url = item.imageURL else { return }
        Task { @MainActor in
            guard let text = await FileTools.recognizeText(url) else {
                NotchModel.shared.announce(Announcement(symbol: "text.viewfinder", tint: .warn, title: "No encontré texto en la imagen"))
                return
            }
            let clip = ClipItem(kind: .text, text: text, app: "Texto de imagen")
            ClipboardStore.shared.insert(clip)
            ClipboardStore.shared.copy(clip)
        }
    }

    /// Text made by VibeNotch (translation, correction): goes on top of the history, ready to paste.
    func addResult(_ text: String, from label: String) {
        let clip = ClipItem(kind: .text, text: text, app: label)
        insert(clip)
        copy(clip)
    }

    func togglePause() {
        Prefs.clipboardPaused.toggle()
        objectWillChange.send()
    }

    func toggleSaved(_ item: ClipItem) {
        if let i = saved.firstIndex(where: { $0.id == item.id || ($0.text != nil && $0.text == item.text) }) {
            let removed = saved.remove(at: i)
            if !history.contains(where: { $0.image == removed.image }) { discardFile(removed) }
        } else {
            saved.insert(item, at: 0)
        }
        scheduleSave()
    }

    func isSaved(_ item: ClipItem) -> Bool {
        saved.contains { $0.id == item.id || ($0.kind == .text && $0.text == item.text) }
    }

    func addSnippet(_ text: String) {
        let t = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !t.isEmpty else { return }
        saved.insert(ClipItem(kind: .text, text: t, app: "Guardado"), at: 0)
        scheduleSave()
    }

    func delete(_ item: ClipItem) {
        history.removeAll { $0.id == item.id }
        discard(item)
        scheduleSave()
    }

    func deleteSaved(_ item: ClipItem) {
        saved.removeAll { $0.id == item.id }
        if !history.contains(where: { $0.id == item.id }) { discardFile(item) }
        scheduleSave()
    }

    func clearHistory() {
        history.forEach(discard)
        history.removeAll()
        scheduleSave()
    }

    private func discard(_ item: ClipItem) {
        if !saved.contains(where: { $0.id == item.id }) { discardFile(item) }
    }

    private func discardFile(_ item: ClipItem) {
        if let url = item.imageURL { try? FileManager.default.removeItem(at: url) }
    }

    private func scheduleSave() {
        saveGeneration += 1
        let gen = saveGeneration
        Task { @MainActor in
            try? await Task.sleep(for: .seconds(1))
            guard gen == ClipboardStore.shared.saveGeneration else { return }
            ClipboardStore.shared.flush()
        }
    }

    func flush() {
        Disk.save(history, "clipboard.json")
        Disk.save(saved, "snippets.json")
    }
}

enum Paster {
    static func paste() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
            let src = CGEventSource(stateID: .combinedSessionState)
            for down in [true, false] {
                let e = CGEvent(keyboardEventSource: src, virtualKey: 9, keyDown: down)
                e?.flags = .maskCommand
                e?.post(tap: .cgAnnotatedSessionEventTap)
            }
        }
    }
}
